// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SatinAlim.Entities;

#nullable disable

namespace SatinAlim.Migrations
{
    [DbContext(typeof(SatinAlimDbContext))]
    [Migration("20240718110741_test2")]
    partial class test2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("satinAlma")
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SatinAlim.Entities.Personel", b =>
                {
                    b.Property<int>("PersonelKod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonelKod"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Pozisyon")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("PersonelKod");

                    b.ToTable("Personel", "satinAlma");
                });

            modelBuilder.Entity("SatinAlim.Entities.SatinAlmaBirim", b =>
                {
                    b.Property<int>("SatinAlmaBirimKod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SatinAlmaBirimKod"));

                    b.Property<string>("BirimAd")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)");

                    b.Property<int>("OnaySayi")
                        .HasColumnType("int");

                    b.HasKey("SatinAlmaBirimKod");

                    b.ToTable("SatinAlmaBirim", "satinAlma");
                });

            modelBuilder.Entity("SatinAlim.Entities.SatinAlmaBirimOnayci", b =>
                {
                    b.Property<int>("SatinAlmaBirimOnayciKod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SatinAlmaBirimOnayciKod"));

                    b.Property<DateTime>("BaslangicTarih")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("BitisTarih")
                        .HasColumnType("datetime");

                    b.Property<int>("OnayPersonelKod")
                        .HasColumnType("int");

                    b.Property<int>("OnaySıra")
                        .HasColumnType("int");

                    b.Property<int>("SatinAlmaBirimKod")
                        .HasColumnType("int");

                    b.Property<bool>("Sureli")
                        .HasColumnType("bit");

                    b.HasKey("SatinAlmaBirimOnayciKod");

                    b.HasIndex("OnayPersonelKod");

                    b.HasIndex("SatinAlmaBirimKod");

                    b.ToTable("SatinAlmaBirimOnayci", "satinAlma");
                });

            modelBuilder.Entity("SatinAlim.Entities.SatinAlmaBirimPersonel", b =>
                {
                    b.Property<int>("SatınAlmaBirimPersonelKod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SatınAlmaBirimPersonelKod"));

                    b.Property<int>("PersonelKod")
                        .HasColumnType("int");

                    b.Property<int>("SatinAlmaBirimKod")
                        .HasColumnType("int");

                    b.HasKey("SatınAlmaBirimPersonelKod");

                    b.HasIndex("PersonelKod");

                    b.HasIndex("SatinAlmaBirimKod");

                    b.ToTable("SatinAlmaBirimPersonel", "satinAlma");
                });

            modelBuilder.Entity("SatinAlim.Entities.SatinAlmaBirimOnayci", b =>
                {
                    b.HasOne("SatinAlim.Entities.Personel", "Personel")
                        .WithMany("SatinAlmaBirimOnaycilar")
                        .HasForeignKey("OnayPersonelKod")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SatinAlim.Entities.SatinAlmaBirim", "SatinAlmaBirim")
                        .WithMany("SatinAlmaBirimOnaycilar")
                        .HasForeignKey("SatinAlmaBirimKod")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Personel");

                    b.Navigation("SatinAlmaBirim");
                });

            modelBuilder.Entity("SatinAlim.Entities.SatinAlmaBirimPersonel", b =>
                {
                    b.HasOne("SatinAlim.Entities.Personel", "Personel")
                        .WithMany("SatinAlmaBirimPersonel")
                        .HasForeignKey("PersonelKod")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SatinAlim.Entities.SatinAlmaBirim", "SatınAlmaBirim")
                        .WithMany("SatinAlmaBirimPersonel")
                        .HasForeignKey("SatinAlmaBirimKod")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Personel");

                    b.Navigation("SatınAlmaBirim");
                });

            modelBuilder.Entity("SatinAlim.Entities.Personel", b =>
                {
                    b.Navigation("SatinAlmaBirimOnaycilar");

                    b.Navigation("SatinAlmaBirimPersonel");
                });

            modelBuilder.Entity("SatinAlim.Entities.SatinAlmaBirim", b =>
                {
                    b.Navigation("SatinAlmaBirimOnaycilar");

                    b.Navigation("SatinAlmaBirimPersonel");
                });
#pragma warning restore 612, 618
        }
    }
}
